### ISSUE TITLE
Update Website for 2023

### ISSUE THREAD

**Issue by PhilippSeidel** [pirates-ophase/pirates-ophase.github.io#44]
- [x] Crew page #46 
  - Crew member images
    - Update images
    - Scale images down to improve performance
  - Crew member name tags
    - Update semester count and bachelor master tag
  - Add new Crew members
- [x] Home page #45 
  - Sponsor logos
  - group image
- [x] Schedule page #47 
  - Generate new schedule images
- [x] Log page #48 
  - Add images from 2022
  - Scale images down to improve performance  
  
- [x] Add imprint page #52

- [x] fix mistakes 
  - [x] fix crew mistakes #50
  - [x] revisit image scaling
  - [x] add billyboy sponsorship #51
  - [x] fix imprint
  - [x] update robots.txt #53 
  - [x] seal moritz
- [x] merge to main #54

**Comment by PhilippSeidel00** [comment]
- [ ] Add imprint page

**Comment by schliz** [comment]
new plank of directors [here](https://github.com/pirates-ophase/pirates-ophase.github.io/pull/46/files#diff-a66a4f7d51fefc17c5356dadf6e6a3d4e75704a26a02b71f0769cc3f1bbcece5L32), [here](https://github.com/pirates-ophase/pirates-ophase.github.io/pull/46/files#diff-a66a4f7d51fefc17c5356dadf6e6a3d4e75704a26a02b71f0769cc3f1bbcece5L35) and [here](https://github.com/pirates-ophase/pirates-ophase.github.io/pull/46/files#diff-a66a4f7d51fefc17c5356dadf6e6a3d4e75704a26a02b71f0769cc3f1bbcece5L38). Please push in [crew_2023](/pirates-ophase/pirates-ophase.github.io/tree/crew_2023)

**Comment by PhilippSeidel** [comment]
add billyboy sponsorship

**Comment by PhilippSeidel** [comment]
revisit image scaling

**Comment by KillingSpark** [comment]
Revisit Image sealing

**Comment by PhilippSeidel** [comment]
> Revisit Image sealing

what do you mean by this? @KillingSpark

**Comment by KillingSpark** [comment]
I think there should be more seals on the pictures.

**Comment by rooedw** [comment]
You should update robots.txt according to the new image folder names for crewmates
